@baseUrl=http://localhost:3000

###
POST {{baseUrl}}/api/expenses
Content-Type: application/json

{
  "id": "4",
  "date": "2025-09-19",
  "description": "Café",
  "payer": "Alice",
  "amount": 3.5
}

###
GET {{baseUrl}}/api/expenses
Accept: application/json


###
POST {{baseUrl}}/api/expenses/reset
Accept: application/json