@hostname = localhost:3000

### Get all expenses
GET http://{{hostname}}/api/transfers
Content-Type: application/json

### Get expense by ID
GET http://{{hostname}}/api/transfers/1
Content-Type: application/json

### Create new expense
POST http://{{hostname}}/api/transfers
Content-Type: application/json

{
  "sourceId": 1,
  "targetId": 2,
  "amount": 10
}