 @baseUrl = http://localhost:3000


### Register a new user
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
"name": "David",
"email": "david@example.com",
"password": "topsecret"
}

### Successful authentication
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
"email": "david@example.com",
"password": "topsecret"
}

### Failed authentication
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
"email": "david@example.com",
"password": "wrongpassword"
}